version: '3.7'

services:
  redis:
    image: 'redis:4.0.6-alpine'
    command: redis-server --requirepass atemporarydevpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
    restart: always

  web:
    build: 
        context: ./services/web
        dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
    - postgres
    secrets:
      - service_account
    restart: always

  celery:
    build: ./services/web
    command: celery -A flask_app.blueprints.analysis.tasks worker -l info -B --loglevel=info
    env_file:
      - ./.env.prod
    volumes:
      - '.:/flask_app'
    secrets:
      - service_account
    restart: always
      
secrets:
   service_account:
     file: /home/pguser/code/secrets/fyllo-service-account.json

volumes:
  redis:
